USE WAREHOUSE COMPUTE_WH;
--parameter for dev , uat , prod
set env = concat(replace('_','_PROD'),'_CICD');

USE ROLE SYSADMIN;

USE DATABASE DB_PROD_CICD;
CREATE SCHEMA IF NOT EXISTS FAST_SCHEMA;
CREATE SCHEMA IF NOT EXISTS ILIFE_SCHEMA;
