-- USE WAREHOUSE COMPUTE_WH;
-- USE ROLE SYSADMIN;
-- USE DATABASE DB_PROD_CICD_RAW;
-- CREATE SCHEMA IF NOT EXISTS FAST_SCHEMA;
-- CREATE SCHEMA IF NOT EXISTS ILIFE_SCHEMA;

USE WAREHOUSE COMPUTE_WH;
--parameter for dev , uat , prod
set env = {{ENV_SUFFIX}};
-- Modify variables here
set DATABASE_RAW_NAME = CONCAT('DB',$env,'_RAW1'); /* Set the name of database here*/
--Database Creation
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS identifier($DATABASE_RAW_NAME);
