USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE VIEW DB{{ENV_SUFFIX}}_RAW.SCH_FAST.TEST_T5
AS 
SELECT * FROM DB{{ENV_SUFFIX}}_RAW.SCH_FAST.HELLO_WORLD;

ALTER VIEW DB{{ENV_SUFFIX}}_RAW.SCH_FAST.TEST_T5 RENAME TO DB{{ENV_SUFFIX}}_RAW.SCH_FAST.a3;

DROP VIEW DB{{ENV_SUFFIX}}_RAW.SCH_FAST.TEST_a3;
