name: Block Feature Merges
on:
    pull_request:
      branches:
        - 'PROD'
  
jobs:
    block-merging:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Block feature branch merges
        run: |
          TARGET_BRANCH=$(jq -r '.pull_request.base.ref' "$GITHUB_EVENT_PATH")
          SOURCE_BRANCH=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
           
        
          if [ "$TARGET_BRANCH" = "PROD" ] && [ "$SOURCE_BRANCH" != "UAT" ]; then
             echo "Merging to PROD from UAT branch is only allowed."
             echo "$TARGET_BRANCH, $SOURCE_BRANCH"
             exit 1
          else
             echo "Source branch is allowed for merge."
             echo "$TARGET_BRANCH, $SOURCE_BRANCH"
          fi
     
           